var albumData = {"albums": [ {"id":0, "title": "RUSH", "cover": "c01.jpeg",  "release": 1974, "type":"Studio", "tracks": [ {"track": "Finding My Way"},
  {"track": "Need Some Love"},
  {"track": "Take a Friend"},
  {"track": "Here Again"},
  {"track": "What You're Doing"},
  {"track": "In the Mood"},
  {"track": "Before and After"},
  {"track": "Working Man"}]},
   {"id":1, "title": "Fly By Night", "cover": "c02.jpeg",  "release": 1975, "type":"Studio", "tracks": [ {"track": "Best I Can"},
  {"track": "Beneath,  Between & Behind"},
  {"track": "By Tor & The Snow Dog"},
  {"track": "(I) At the Tobes of Hades"},
  {"track": "(II) Across The Styx"},
  {"track": "(III) Of The Battle"},
  {"track": "(IV) Epilogue"},
  {"track": "Fly By Night"},
  {"track": "Making Memories"},
  {"track": "Rivendell"},
  {"track": "In The End"}]},
     {"id":2, "title": "Caress of Steel", "cover": "c03.jpeg",  "release": 1975, "type":"Studio", "tracks": [ {"track": "Bastille Day"},
  {"track": "I Think I'm Going Bald"},
  {"track": "Lakeside Park"},
  {"track": "The Necromancer"},
  {"track": "(I) Into The Darkness"},
  {"track": "(II) Under The Shadow"},
  {"track": "(III) Return Of The Prince"},
  {"track": "The Fountain Of Lamneth"},
  {"track": "(I) In The Valley"},
  {"track": "(II) Didacts And Narpets"},
  {"track": "(III) No One At The Bridge"},
  {"track": "(IV) Panacea"},
  {"track": "(V) Bacchus Plateau"},
  {"track": "(VI) The Fountain"}]},
 {"id":3, "title": "2112", "cover": "c04.jpeg",  "release": 1976, "type":"Studio", "tracks": [ {"track": "(I) Overture"},
  {"track": "(II) The Temples Of Syrinx"},
  {"track": "(III) Discovery"},
  {"track": "(IV) Presentation"},
  {"track": "(V) Oracle: The Dream"},
  {"track": "(VI) Soliloquy"},
  {"track": "(VII) Grand Finale"},
  {"track": "A Passage To Bangkok"},
  {"track": "The Twilight Zone"},
  {"track": "Lessons"},
  {"track": "Tears"},
  {"track": "Something For Nothing"}]},
 {"id":4, "title": "All the World's a Stage", "cover": "c05.jpeg",  "release": 1976, "type":"Live", "tracks": [ {"track": "Bastille Day"},
  {"track": "Anthem"},
  {"track": "Fly By Night/In The Mood"},
  {"track": "Something for Nothing"},
  {"track": "Lakeside Park"},
  {"track": "(I) Overture"},
  {"track": "(II) The Temples Of Syrinx"},
  {"track": "(III) Presentation"},
  {"track": "(IV) Soliloquy"},
  {"track": "(V) Grand Finale"},
  {"track": "By-Tor & The Snow Dog"},
  {"track": "In The End"},
  {"track": "Working Man/Finding My Way"},
  {"track": "What You're Doing"}]},
 {"id":5, "title": "Farewell to Kings", "cover": "c06.jpeg",  "release": 1977, "type":"Studio", "tracks": [ {"track": "A Farewell To Kings"},
  {"track": "Xanadu"},
  {"track": "Closer To The Heart"},
  {"track": "Cinderella Man"},
  {"track": "Madrigal"},
  {"track": "Cygnus X-1"}]},
  {"id":6, "title": "Hemispheres", "cover": "c08.jpeg",  "release": 1978, "type":"Studio", "tracks": [ {"track": "Hemispheres"},
  {"track": "(I) Prelude"},
  {"track": "(II) Apollo/Dionysus"},
  {"track": "(III) Armageddon"},
  {"track": "(IV) Cygnus"},
  {"track": "(V) The Sphere"},
  {"track": "Circumstances"},
  {"track": "The Trees"},
  {"track": "La Villa Strangiato"}]},
   {"id":7, "title": "Permanent Waves", "cover": "c09.jpeg",  "release": 1980, "type":"Studio", "tracks": [ {"track": "The Spirit Of Radio"},
  {"track": "Freewill"},
  {"track": "Jacob's Ladder"},
  {"track": "Entre Nous"},
  {"track": "Different Strings"},
  {"track": "Natural Science"},
  {"track": "(I) Tide Pools"},
  {"track": "(II) Hyperspace"},
  {"track": "(III) Permanent Waves"}]},
  {"id":8, "title": "Moving Pictures", "cover": "c10.jpeg",  "release": 1981, "type":"Studio", "tracks": [ {"track": "Tom Sawyer"},
  {"track": "Red Barchetta"},
  {"track": "YYZ"},
  {"track": "Limelight"},
  {"track": "The Camera Eye"},
  {"track": "Witch Hunt (Part III of Fear)"},
  {"track": "Vital Signs"}]},
   {"id":9, "title": "Exit...Stage Left", "cover": "c11.jpeg",  "release": 1981, "type":"Live", "tracks": [ {"track": "Spirit of Radio"},
  {"track": "Red Barchetta"},
  {"track": "YYZ"},
  {"track": "A Passage To Bangkok"},
  {"track": "Closer To The Heart"},
  {"track": "Beneath,  Between & Behind"},
  {"track": "Jacob's Ladder"},
  {"track": "Broons Bane"},
  {"track": "The Trees"},
  {"track": "Xanadu"},
  {"track": "Freewill"},
  {"track": "Tom Sawyer"},
  {"track": "La Villa Strangiato"}]},
 {"id":10, "title": "Signals", "cover": "c12.jpeg",  "release": 1982, "type":"Studio", "tracks": [ {"track": "Subdivisions"},
  {"track": "The Analog Kid"},
  {"track": "Chemistry"},
  {"track": "Digital Man"},
  {"track": "The Weapon"},
  {"track": "New World Man"},
  {"track": "Losing It"},
  {"track": "Countdown"}]},
   {"id":11, "title": "Grace under Pressure", "cover": "c13.jpeg",  "release": 1984, "type":"Studio", "tracks": [ {"track": "Distant Early Warning"},
  {"track": "Afterimage"},
  {"track": "Red Sector 'A'"},
  {"track": "The Enemy Within"},
  {"track": "The Body Electric"},
  {"track": "Kid Gloves"},
  {"track": "Red Lenses"},
  {"track": "Between The Wheels"}]},
   {"id":12, "title": "Power Windows", "cover": "c14.jpeg",  "release": 1985, "type":"Studio", "tracks": [ {"track": "The Big Money"},
  {"track": "Grand Designs"},
  {"track": "Manhattan Project"},
  {"track": "Marathon"},
  {"track": "Territories"},
  {"track": "Middletown Dreams"},
  {"track": "Emotion Detector"},
  {"track": "Mystic Rhythms"}]},
   {"id":13, "title": "Hold Your Fire", "cover": "c33.jpeg",  "release": 1987, "type":"Studio", "tracks": [ {"track": "Force Ten"},
  {"track": "Time Stands Still"},
  {"track": "Open Secrets"},
  {"track": "Second Nature"},
  {"track": "Prime Mover"},
  {"track": "Lock And Key"},
  {"track": "Mission"},
  {"track": "Turn The Page"},
  {"track": "Tai Shan"},
  {"track": "High Water"}]},
 {"id":14, "title": "A Show of Hands", "cover": "c151.jpeg",  "release": 1989, "type":"Live", "tracks": [ {"track": "Intro"},
  {"track": "The Big Money"},
  {"track": "Subdivisions"},
  {"track": "Marathon"},
  {"track": "Turn The Page"},
  {"track": "Manhattan Project"},
  {"track": "Mission"},
  {"track": "Distant Early Warning"},
  {"track": "Mystic Rhythms"},
  {"track": "Witch Hunt"},
  {"track": "The Rhythm Method"},
  {"track": "Force Ten"},
  {"track": "Time Stands Still"},
  {"track": "Red Sector 'A'"},
  {"track": "Closer The The Heart"}]},
   {"id":15, "title": "Presto", "cover": "c161.jpeg",  "release": 1989, "type":"Studio", "tracks": [ {"track": "Show Don't Tell"},
  {"track": "Chain Lightning"},
  {"track": "The Pass"},
  {"track": "War Paint"},
  {"track": "Scars"},
  {"track": "Presto"},
  {"track": "Superconductor"},
  {"track": "Anagram (For Mongo)"},
  {"track": "Red Tide"},
  {"track": "Hand Over Fist"},
  {"track": "Available Light"}]},
  {"id":16, "title": "Chronicles", "cover": "c17.jpeg",  "release": 1990, "type":"Studio", "tracks": [ {"track": "Finding My Way"},
  {"track": "Working Man"},
  {"track": "Fly By Night"},
  {"track": "Anthem"},
  {"track": "Bastille Day"},
  {"track": "Lakeside Park"},
  {"track": "The Temples Of Syrinx"},
  {"track": "What You're Doing (Live)"},
  {"track": "A Farewell To Kings"},
  {"track": "Closer To The Heart"},
  {"track": "The Trees"},
  {"track": "La Villa Stangiato"},
  {"track": "Freewill"},
  {"track": "Spirit Of Radio"}]},
  {"id":17, "title": "Roll the Bones", "cover": "c18.jpeg",  "release": 1991, "type":"Studio", "tracks": [ {"track": "Dreamline"},
  {"track": "Bravado"},
  {"track": "Roll The Bones"},
  {"track": "Face Up"},
  {"track": "Where's My Thing?"},
  {"track": "(Part IV,  'Gangster Of Boats')"},
  {"track": "The Big Wheel"},
  {"track": "Heresy"},
  {"track": "Ghost Of A Chance"},
  {"track": "Neurotica"},
  {"track": "You Bet Your Life"}]},
   {"id":18, "title": "Counterparts", "cover": "c19.jpeg",  "release": 1993, "type":"Studio", "tracks": [ {"track": "Animate"},
  {"track": "Stick It Out"},
  {"track": "Cut To The Chase"},
  {"track": "Nobody's Hero"},
  {"track": "Between Sun & Moon"},
  {"track": "Alien Shore"},
  {"track": "The Speed Of Love"},
  {"track": "Double Agent"},
  {"track": "Leave That Thing Alone"},
  {"track": "Cold Fire"},
  {"track": "Everyday Glory"}]},
  {"id":19, "title": "Test for Echo", "cover": "c38.jpeg",  "release": 1996, "type":"Studio", "tracks": [ {"track": "Test For Echo"},
  {"track": "Driven"},
  {"track": "Half The World"},
  {"track": "Colour Of Light"},
  {"track": "Time and Motion"},
  {"track": "Totem"},
  {"track": "Dog Years"},
  {"track": "Virtuality"},
  {"track": "Resist"},
  {"track": "Limbo"},
  {"track": "Carve Away The Stone"}]},
  {"id":20, "title": "Retrospective (1974-1980)", "cover": "c21.jpeg",  "release": 1997, "type":"Studio", "tracks": [ {"track": "The Spirit Of Radio"},
  {"track": "The Trees"},
  {"track": "Something For Nothing"},
  {"track": "Freewill"},
  {"track": "Xanadu"},
  {"track": "Bastille Day"},
  {"track": "By-Tor And The Snow Dog"},
  {"track": "Anthem"},
  {"track": "Closer To The Heart"},
  {"track": "2112 Overture"},
  {"track": "The Temples Of Syrinx"},
  {"track": "La Villa Strangiato"},
  {"track": "Fly By Night"},
  {"track": "Finding My Way"}]},
   {"id":21, "title": "Retrospectives II (1981-1987)", "cover": "c22.jpeg",  "release": 1997, "type":"Studio", "tracks": [ {"track": "The Big Money"},
  {"track": "Red Barchetta"},
  {"track": "Subdivisions"},
  {"track": "Time Stands Still"},
  {"track": "Mystic Rhythms"},
  {"track": "The Analog Kid"},
  {"track": "Distant Early Warning"},
  {"track": "Marathon"},
  {"track": "The Body Electric"},
  {"track": "Mission"},
  {"track": "Limelight"},
  {"track": "Red Sector 'A'"},
  {"track": "New World Man"},
  {"track": "Tom Sawyer"},
  {"track": "Force Ten"}]},
   {"id":22, "title": "Different Stages", "cover": "c23.jpeg",  "release": 1998, "type":"Live", "tracks": [ {"track": "Dreamline"},
  {"track": "Limelight"},
  {"track": "Driven"},
  {"track": "Bravado"},
  {"track": "Animate"},
  {"track": "Show Don't Tell"},
  {"track": "The Trees"},
  {"track": "Nobody's Hero"},
  {"track": "Closer To The Heart"}]},
   {"id":23, "title": "Vapor Trails", "cover": "c24.jpeg",  "release": 2002, "type":"Studio", "tracks": [ {"track": "One Little Victory"},
  {"track": "Ceiling Unlimited"},
  {"track": "Ghost Rider"},
  {"track": "Peaceable Kingdom"},
  {"track": "The Stars Look Down"},
  {"track": "How It Is"},
  {"track": "Vapor Trail"},
  {"track": "Secret Touch"},
  {"track": "Earthshine"},
  {"track": "Sweet Miracle"},
  {"track": "Nocturne"},
  {"track": "Freeze (Part IV of 'Fear')"},
  {"track": "Out Of The Cradle"}]},
   {"id":24, "title": "The Spirit of Radio", "cover": "c25.jpeg",  "release": 2003, "type":"Studio", "tracks": [ {"track": "Working Man"},
  {"track": "Fly By Night"},
  {"track": "2112 Overture/The Temples Of Syrinx"},
  {"track": "Closer To The Heart"},
  {"track": "The Trees"},
  {"track": "The Spirit Of Radio"},
  {"track": "Freewill"},
  {"track": "Limelight"},
  {"track": "Tom Sawyer"},
  {"track": "Red Barchetta"},
  {"track": "New World Man"},
  {"track": "Subdivisions"},
  {"track": "Distant Early Warning"},
  {"track": "The Big Money"},
  {"track": "Force Ten"},
  {"track": "Time Stand Still"}]},
   {"id":25, "title": "RUSH in Rio", "cover": "c26.jpeg",  "release": 2003, "type":"Live", "tracks": [ {"track": "Tom Sawyer"},
  {"track": "Distant Early Warning"},
  {"track": "New World Man"},
  {"track": "Roll The Bones"},
  {"track": "Earthshine"},
  {"track": "YYZ"},
  {"track": "The Pass"},
  {"track": "Bravado"},
  {"track": "The Big Money"},
  {"track": "The Trees"},
  {"track": "Free Will"},
  {"track": "Closer To The Heart"},
  {"track": "Natural Science"},
  {"track": "One Little Victory"},
  {"track": "Driven"},
  {"track": "Ghost Rider"},
  {"track": "Secret Touch"},
  {"track": "Dreamline"},
  {"track": "Red Sector A"},
  {"track": "Leave That Thing Alone"},
  {"track": "O Baterista"},
  {"track": "Resist"},
  {"track": "2112 Overture/The Temples of Syrinx"},
  {"track": "Limelight"},
  {"track": "La Villa Strangiato"},
  {"track": "The Spirit of Radio"},
  {"track": "By-Tor & The Snow Dog"},
  {"track": "Cygnus X-1"},
  {"track": "Working Man"},
  {"track": "Between Sun & Moon (Bonus Track)"},
  {"track": "Vital Signs (Bonus Track)"}]},
   {"id":26, "title": "Feedback", "cover": "c28.jpeg",  "release": 2004, "type":"Studio", "tracks": [ {"track": "Summertime Blues"},
  {"track": "Heart Full of Soul"},
  {"track": "The Seeker"},
  {"track": "For What It’s Worth"},
  {"track": "Shapes of Things"},
  {"track": "Mr. Soul"},
  {"track": "Crossroads"},
  {"track": "Seven and Seven Is"}]},
  {"id":27, "title": "R30", "cover": "c291.jpeg",  "release": 2005, "type":"Live", "tracks": [ {"track": "R-30 Overture"},
  {"track": "The Spirit of Radio"},
  {"track": "Force Ten"},
  {"track": "Animate"},
  {"track": "Subdivisions"},
  {"track": "Earthshine"},
  {"track": "Red Barchetta"},
  {"track": "Roll The Bones"},
  {"track": "The Seeker"},
  {"track": "Tom Sawyer"},
  {"track": "Dreamline"},
  {"track": "Between the Wheels"},
  {"track": "Der Trommler"},
  {"track": "Resist"},
  {"track": "Heart Full of Soul"},
  {"track": "2112"},
  {"track": "Xanadu"},
  {"track": "Working Man"},
  {"track": "Summertime Blues"},
  {"track": "Crossroads"},
  {"track": "Limelight"}]},
   {"id":28, "title": "Snakes & Arrows", "cover": "c31.jpeg",  "release": 2007, "type":"Studio", "tracks": [ {"track": "Far Cry"},
  {"track": "Armor and Sword"},
  {"track": "Workin' Them Angels"},
  {"track": "The Larger Bowl"},
  {"track": "Spindrift"},
  {"track": "The Main Monkey Business"},
  {"track": "The Way the Wind Blows"},
  {"track": "Hope"},
  {"track": "Faithless"},
  {"track": "Bravest Face"},
  {"track": "Good News First"},
  {"track": "Malignant Narcissism"},
  {"track": "We Hold On"}]},
  {"id":29, "title": "Snakes & Arrows - Live", "cover": "c36.jpeg",  "release": 2008, "type":"Live", "tracks": [ {"track": "Limelight"},
  {"track": "Digital Man"},
  {"track": "Entre Nous"},
  {"track": "Mission"},
  {"track": "Freewill"},
  {"track": "The Main Monkey Business"},
  {"track": "The Larger Bowl"},
  {"track": "Secret Touch"},
  {"track": "Circumstances"},
  {"track": "Between The Wheels"},
  {"track": "Dreamline"},
  {"track": "Far Cry"},
  {"track": "Workin' Them Angels"},
  {"track": "Armor and Sword"},
  {"track": "Spindrift"},
  {"track": "The Way the Wind Blows"},
  {"track": "Subdivisions"},
  {"track": "Natural Science"},
  {"track": "Witch Hunt"},
  {"track": "Malignant Narcissism - De Slagwerker (Drum Solo)"},
  {"track": "Hope"},
  {"track": "Distant Early Warning"},
  {"track": "The Spirit of Radio"},
  {"track": "Tom Sawyer"},
  {"track": "One Little Victory"},
  {"track": "A Passage to Bangkok"},
  {"track": "YYZ"}]},
 {"id":30, "title": "Retrospective III (1989-2008)", "cover": "c40.jpeg",  "release": 2009, "type":"Studio", "tracks": [ {"track": "One Little Victory (remix)"},
  {"track": "Dreamline"},
  {"track": "Workin' Them Angels"},
  {"track": "Presto"},
  {"track": "Bravado"},
  {"track": "Driven"},
  {"track": "The Pass"},
  {"track": "Animate"},
  {"track": "Roll the Bones"},
  {"track": "Ghost of a Chance (live)"},
  {"track": "Nobody's Hero"},
  {"track": "Leave That Thing Alone"},
  {"track": "Earthshine (remix)"},
  {"track": "Far Cry"}]},
   {"id":31, "title": "Time Machine 2011: Live in Cleveland", "cover": "c35.jpeg",  "release": 2011, "type":"Live", "tracks": [ {"track": "The Spirit of Radio"},
  {"track": "Time Stand Still"},
  {"track": "Presto"},
  {"track": "Stick It Out"},
  {"track": "Workin' Them Angels"},
  {"track": "Leave That Thing Alone"},
  {"track": "Faithless"},
  {"track": "BU2B"},
  {"track": "Freewill"},
  {"track": "Marathon"},
  {"track": "Subdivisions"},
  {"track": "Tom Sawyer"},
  {"track": "Red Barchetta"},
  {"track": "YYZ"},
  {"track": "Limelight"},
  {"track": "The Camera Eye"},
  {"track": "Witch Hunt"},
  {"track": "Vital Signs"},
  {"track": "Caravan"},
  {"track": "Moto Perpetuo (Drum solo)"},
  {"track": "O'Malley's Break (acoustic solo)"},
  {"track": "Closer to the Heart"},
  {"track": "2112 (Overture/The Temples of Syrinx)"},
  {"track": "Far Cry"},
  {"track": "La Villa Strangiato"},
  {"track": "Working Man"}]},
   {"id":32, "title": "Clockwork Angels", "cover": "c37.jpeg",  "release": 2012, "type":"Studio", "tracks": [ {"track": "Caravan"},
  {"track": "BU2B"},
  {"track": "Clockwork Angels"},
  {"track": "The Anarchist"},
  {"track": "Carnies"},
  {"track": "Halo Effect"},
  {"track": "Seven Cities of Gold"},
  {"track": "The Wreckers"},
  {"track": "Headlong Flight"},
  {"track": "BU2B2"},
  {"track": "Wish Them Well"},
  {"track": "The Garden"}]} ]};